# -*- coding: utf-8 -*-
"""
Created on Fri Apr 28 10:27:52 2023

@author: Marko
"""

import matplotlib.pyplot as plt
import numpy as np

ypoints = np.array([3,8,1,10])
plt.plot(ypoints, marker = 'o')
plt.show()
plt.plot(ypoints,  marker = '*')
plt.show()
plt.plot(ypoints,  marker = '.')
plt.show()
plt.plot(ypoints,  marker = ',')
plt.show()
plt.plot(ypoints,  marker = 'x')
plt.show()
plt.plot(ypoints,  marker = 'X')
plt.show()
plt.plot(ypoints,  marker = '+')
plt.show()
plt.plot(ypoints,  marker = 'P')
plt.show()
plt.plot(ypoints,  marker = 's')
plt.show()
plt.plot(ypoints,  marker = 'D')
plt.show()
plt.plot(ypoints,  marker = 'd')
plt.show()
plt.plot(ypoints,  marker = 'p')
plt.show()
plt.plot(ypoints,  marker = 'H')
plt.show()
plt.plot(ypoints,  marker = 'h')
plt.show()
plt.plot(ypoints,  marker = 'v')
plt.show()
plt.plot(ypoints,  marker = '^')
plt.show()
plt.plot(ypoints,  marker = '<')
plt.show()
plt.plot(ypoints,  marker = '>')
plt.show()
plt.plot(ypoints,  marker = '1')
plt.show()
plt.plot(ypoints,  marker = '2')
plt.show()
plt.plot(ypoints,  marker = '3')
plt.show()
plt.plot(ypoints,  marker = '4')
plt.show()
plt.plot(ypoints,  marker = '|')
plt.show()
plt.plot(ypoints,  marker = '_')
plt.show()

plt.plot(ypoints, 'o:r')
plt.show()
plt.plot(ypoints, 'o-r')
plt.show()
plt.plot(ypoints, 'o--r')
plt.show()
plt.plot(ypoints, 'o-.r')
plt.show()
plt.plot(ypoints, 'o:g')
plt.show()
plt.plot(ypoints, 'o:b')
plt.show()
plt.plot(ypoints, 'o:c')
plt.show()
plt.plot(ypoints, 'o:m')
plt.show()
plt.plot(ypoints, 'o:y')
plt.show()
plt.plot(ypoints, 'o:k')
plt.show()
plt.plot(ypoints, 'o:w')
plt.show()
# markersize = ms
plt.plot(ypoints, marker = 'o', ms = 20)
plt.show()
# markeredgecolor = mec
plt.plot(ypoints, marker = 'o', ms = 20, mec = 'k')
plt.show()
# markerfacecolor = mfc
plt.plot(ypoints, marker = 'o', ms = 20, mec = 'k', mfc = 'c')
plt.show()
# hexadecimal color
plt.plot(ypoints, marker = 'o', ms = 20, mec = '#4caf50', mfc = '#4caf50')
plt.show()
# вбо один з 140 підтримуваних назв кольорів
plt.plot(ypoints, marker = 'o', ms = 20, mec = '#hotpink', mfc = 'hotpink')
plt.show()
